export const PRICING_V3 = {
  TRIAL: {
    DURATION_DAYS: 3,
    INCLUDED_CAMPAIGNS: 1,
    INCLUDED_MESSAGES: 10,
    INCLUDED_DETAIL_VIEWS: 30,
    DAILY_DB_VIEW_LIMIT: 30,
  },
  STANDARD: {
    MONTHLY_FEE: 99_000,
    CAMPAIGN_MONTHLY_LIMIT: 3,
    MESSAGE_MONTHLY_LIMIT: 100,
    DETAIL_VIEW_FREE_QUOTA_MONTHLY: 100,
    DETAIL_VIEW_OVERAGE_PRICE: 100,
    DAILY_DB_VIEW_LIMIT: 100,
    SHOP_COMMISSION_RATE: 10.0,
  },
  PRO: {
    MONTHLY_FEE: 330_000,
    ANNUAL_FEE: 3_168_000,
    ANNUAL_MONTHLY_EQUIVALENT: 264_000,
    INCLUDED_MESSAGES_MONTHLY: 500,
    OVERAGE_MESSAGE_PRICE: 700,
    DAILY_DB_VIEW_LIMIT: -1,
    DETAIL_VIEW_FREE_QUOTA_MONTHLY: -1,
    SHOP_COMMISSION_RATE: 8.0,
  },
  RESTRICTED: {
    DURATION_DAYS: 30,
    DAILY_DB_VIEW_LIMIT: 10,
    CAMPAIGN_LIMIT: 0,
    MESSAGE_LIMIT: 0,
    DETAIL_VIEW_LIMIT: 0,
  },
} as const

export const CREATOR_PROTECTION = {
  MONTHLY_PROPOSAL_LIMIT_DEFAULT: 30,
  REPROPOSAL_COOLDOWN_DAYS: 90,
  MIN_MATCH_SCORE_TO_SEND: 70,
} as const

export const ABUSE_DETECTION = {
  RAPID_DETAIL_VIEW_PER_HOUR: 50,
  MASS_GROUP_ADD_PER_HOUR: 300,
  REPETITIVE_SEARCH_THRESHOLD: 20,
} as const
